package container

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"io"
	"time"

	"cyberstrike-ai/internal/egress"
)

// RuntimeID is the CyberStrikeAI-owned identifier for a conversation runtime.
// It is intentionally separate from the Docker container ID exposed by an
// engine implementation.
type RuntimeID string

// Status describes the control-plane view of a conversation runtime.
type Status string

const (
	StatusCreating Status = "creating"
	StatusStopped  Status = "stopped"
	StatusStarting Status = "starting"
	StatusRunning  Status = "running"
	StatusStopping Status = "stopping"
	StatusFailed   Status = "failed"
)

// NetworkMode is deliberately closed. NetworkNone remains valid for durable
// runtimes created before stage 4; all newly generated conversation runtimes
// use an isolated per-conversation internal network.
type NetworkMode string

const (
	NetworkNone     NetworkMode = "none"
	NetworkInternal NetworkMode = "internal"
)

var (
	ErrNotFound             = errors.New("container runtime not found")
	ErrAlreadyExists        = errors.New("container runtime already exists")
	ErrEngineUnavailable    = errors.New("container engine unavailable")
	ErrInvalidSpecification = errors.New("invalid container runtime specification")
	ErrArchitectureMismatch = errors.New("container image architecture mismatch")
	ErrImageDigestMismatch  = errors.New("container image digest mismatch")
	ErrRegistryUnavailable  = errors.New("container image registry unavailable")
	ErrRuntimeStateConflict = errors.New("container runtime state conflict")
	ErrEngineIncompatible   = errors.New("container engine does not satisfy the security baseline")
	ErrExecQueueFull        = errors.New("container exec queue is full")
	ErrRuntimeNotReady      = errors.New("container runtime readiness validation failed")
)

// EngineInfo is a read-only description of the connected container engine.
type EngineInfo struct {
	Available       bool
	Version         string
	APIVersion      string
	Architecture    string
	RawArchitecture string
	OperatingSys    string
	CgroupVersion   string
	MemoryLimit     bool
	CPULimit        bool
	PIDsLimit       bool
	SecurityOptions []string
}

// ImageReference requires an immutable digest in addition to the repository.
// Tags may be displayed by the UI, but implementations must create containers
// from Repository@Digest and verify ResolvedDigest before reporting readiness.
type ImageReference struct {
	Repository     string
	Digest         string
	Platform       string
	ResolvedDigest string
}

// ImageInspection is returned by both remote manifest inspection and local
// image verification. ManifestDigest is the immutable distribution digest;
// ImageID is populated only for a local engine image.
type ImageInspection struct {
	Reference      ImageReference
	ManifestDigest string
	Platforms      []string
	ImageID        string
	SizeBytes      int64
	Local          bool
}

// ResourceLimits contains the limits that every runtime implementation must
// enforce. Zero is not interpreted as unlimited; validation rejects it.
type ResourceLimits struct {
	NanoCPUs          int64
	MemoryBytes       int64
	PIDs              int64
	NoFileSoft        uint64
	NoFileHard        uint64
	WorkspaceBytes    int64
	MaxConcurrentExec int
	MaxQueuedExec     int
	LogMaxBytes       int64
	LogMaxFiles       int
}

// SecurityProfile describes non-negotiable container isolation controls.
// The Docker implementation will translate this contract into engine options.
type SecurityProfile struct {
	ReadOnlyRootFS      bool
	NoNewPrivileges     bool
	DropAllCapabilities bool
	NetworkMode         NetworkMode
	SeccompProfile      string
	TmpfsBytes          int64
}

// WorkspaceSpec makes persistence and deletion independent from the container
// lifecycle. VolumeName is generated by the control plane, never supplied by a
// user as an arbitrary host path.
type WorkspaceSpec struct {
	Persistent bool
	VolumeName string
	MountPath  string
}

// EgressGatewayResources contains the independently enforced limits for the
// per-conversation egress sidecar. The gateway never receives a workspace or
// an exec queue, so those agent-only limits are deliberately absent here.
type EgressGatewayResources struct {
	NanoCPUs    int64
	MemoryBytes int64
	PIDs        int64
	NoFileSoft  uint64
	NoFileHard  uint64
	TmpfsBytes  int64
	LogMaxBytes int64
	LogMaxFiles int
}

// EgressBoundarySnapshotSpec identifies the immutable control-plane snapshot
// that must be mounted read-only and verified before the gateway is ready. The
// canonical JSON stays in the trusted snapshot store, never in Agent input.
type EgressBoundarySnapshotSpec struct {
	ID     string
	SHA256 string
}

// EgressUpstreamRouteSpec identifies the immutable gateway-only route file.
// The document itself may contain proxy credentials and is never serialized
// into the runtime specification, labels, command line, or Agent environment.
type EgressUpstreamRouteSpec struct {
	ID     string
	SHA256 string
}

// EgressAuthProfilesSpec identifies the immutable gateway-only credential
// document. The runtime specification contains only this safe reference.
type EgressAuthProfilesSpec struct {
	ID     string
	SHA256 string
}

// EgressTLSAuthoritySpec binds one short-lived conversation CA. The Agent is
// given only CertificateSHA256 material; the private key mount is gateway-only.
type EgressTLSAuthoritySpec struct {
	ID                 string
	BoundarySnapshotID string
	CertificateSHA256  string
	PrivateKeySHA256   string
}

// EgressGatewaySpec pins the only image that may bridge a conversation's
// internal network to its dedicated egress network.
type EgressGatewaySpec struct {
	Image            ImageReference
	Resources        EgressGatewayResources
	BoundarySnapshot *EgressBoundarySnapshotSpec `json:",omitempty"`
	UpstreamRoute    *EgressUpstreamRouteSpec    `json:",omitempty"`
	AuthProfiles     *EgressAuthProfilesSpec     `json:",omitempty"`
	TLSAuthority     *EgressTLSAuthoritySpec     `json:",omitempty"`
}

// RuntimeSpec is the desired immutable specification for one conversation.
type RuntimeSpec struct {
	ID             RuntimeID
	ConversationID string
	Image          ImageReference
	Resources      ResourceLimits
	Security       SecurityProfile
	Workspace      WorkspaceSpec
	Readiness      ReadinessPolicy
	// Omitempty preserves the exact JSON and digest of durable pre-gateway
	// specifications. Existing runtimes therefore remain inspectable until an
	// explicit rebuild performs the controlled topology upgrade.
	EgressGateway *EgressGatewaySpec `json:",omitempty"`
}

// Runtime is the engine-observed state returned to the control plane.
type Runtime struct {
	ID             RuntimeID
	ConversationID string
	ProviderID     string
	Image          ImageReference
	Status         Status
	CreatedAt      time.Time
	UpdatedAt      time.Time
	LastError      string
	Warnings       []string
	SpecDigest     string
}

// ResourceUsage is a bounded, credential-free snapshot of live Docker
// accounting. It is intentionally limited to aggregate counters that are safe
// to expose in the container management UI.
type ResourceUsage struct {
	Available        bool    `json:"available"`
	CPUPercent       float64 `json:"cpuPercent,omitempty"`
	MemoryUsageBytes uint64  `json:"memoryUsageBytes,omitempty"`
	MemoryLimitBytes uint64  `json:"memoryLimitBytes,omitempty"`
	PIDs             uint64  `json:"pids,omitempty"`
	NetworkRXBytes   uint64  `json:"networkRxBytes,omitempty"`
	NetworkTXBytes   uint64  `json:"networkTxBytes,omitempty"`
	BlockReadBytes   uint64  `json:"blockReadBytes,omitempty"`
	BlockWriteBytes  uint64  `json:"blockWriteBytes,omitempty"`
}

// RuntimeComponentObservation describes one engine component without
// returning environment variables, mounts, labels, commands, or credentials.
type RuntimeComponentObservation struct {
	ProviderID  string        `json:"providerId"`
	Status      Status        `json:"status"`
	ImageDigest string        `json:"imageDigest"`
	LastError   string        `json:"lastError,omitempty"`
	Warnings    []string      `json:"warnings,omitempty"`
	Resources   ResourceUsage `json:"resources"`
}

// RuntimeObservation is the live, read-only engine view used by management
// pages. Inspect validates immutable identity, gateway topology, policy DNS,
// images, and security controls before this projection is returned.
type RuntimeObservation struct {
	Agent            RuntimeComponentObservation  `json:"agent"`
	Gateway          *RuntimeComponentObservation `json:"gateway,omitempty"`
	PolicyDNSStatus  string                       `json:"policyDnsStatus"`
	PolicyDNSAddress string                       `json:"policyDnsAddress,omitempty"`
	WorkspaceStatus  string                       `json:"workspaceStatus"`
	ObservedAt       time.Time                    `json:"observedAt"`
}

// RuntimeSpecDigest is the stable digest embedded in an immutable container
// label and compared with the durable database specification during every
// lifecycle operation.
func RuntimeSpecDigest(spec RuntimeSpec) string {
	encoded, _ := json.Marshal(spec)
	sum := sha256.Sum256(encoded)
	return "sha256:" + hex.EncodeToString(sum[:])
}

type StopOptions struct {
	Timeout time.Duration
}

type DeleteOptions struct {
	RemoveWorkspace bool
}

type RebuildOptions struct {
	Spec                          RuntimeSpec
	RemoveWorkspace               bool
	AuthorizedWorkspaceSpecDigest string
}

// ExecStream identifies the Docker multiplexed output stream without exposing
// engine-specific frame types outside this package.
type ExecStream string

const (
	ExecStreamStdout ExecStream = "stdout"
	ExecStreamStderr ExecStream = "stderr"
)

// ExecRequest is an argv-based, non-interactive command request for one
// already-initialized conversation runtime. Callers never provide a Docker
// provider ID; RuntimeSpec is used to verify the durable immutable identity.
type ExecRequest struct {
	Command    []string
	WorkingDir string
	Env        []string
	// TTY requests a non-interactive pseudo terminal. Stdin stays detached;
	// stdout/stderr are returned as Docker's single raw TTY stream.
	TTY bool
}

// ExecResult contains only engine-observed process metadata. Output is sent to
// the supplied sink so upper layers can retain their existing bounded streaming
// and spill behavior.
type ExecResult struct {
	ExecID   string
	ExitCode int
}

type ExecOutputSink func(stream ExecStream, chunk []byte) error

// RuntimeExecutor is deliberately separate from RuntimeManager so lifecycle
// fakes and read-only collaborators do not accidentally become command
// execution surfaces.
type RuntimeExecutor interface {
	Exec(ctx context.Context, spec RuntimeSpec, request ExecRequest, sink ExecOutputSink) (ExecResult, error)
}

// ActivityStreamOptions bounds the historical gateway-log tail delivered
// before following new events.
type ActivityStreamOptions struct {
	Tail int
	// All replays the gateway's complete bounded Docker log before following.
	// It is reserved for the trusted persistent audit collector; HTTP callers
	// remain limited to Tail <= 500.
	All bool
}

type RuntimeActivitySink func(egress.ActivityEvent) error

// RuntimeActivityStreamer is separate from RuntimeManager because a live log
// subscription is a read-only, long-lived capability that lifecycle fakes and
// unrelated collaborators should not acquire accidentally.
type RuntimeActivityStreamer interface {
	StreamEgressActivity(context.Context, RuntimeSpec, ActivityStreamOptions, RuntimeActivitySink) error
}

// RuntimeEgressHealthController is intentionally separate from lifecycle and
// execution. Implementations may expose only a verified, fixed manual-recovery
// signal for the owned per-conversation gateway.
type RuntimeEgressHealthController interface {
	RecoverEgressHealth(context.Context, RuntimeSpec) error
}

// ToolOutputWriteRequest contains a complete oversized tool output stream. The
// runtime implementation owns the destination and never accepts a host path or
// arbitrary container path from the request.
type ToolOutputWriteRequest struct {
	FileName string
	Content  io.Reader
	Size     int64
}

// RuntimeToolOutputWriter persists oversized output inside the verified
// conversation workspace and returns the container-visible file reference.
type RuntimeToolOutputWriter interface {
	WriteToolOutput(ctx context.Context, spec RuntimeSpec, request ToolOutputWriteRequest) (string, error)
}

// WorkspaceFileWriteRequest carries bytes for one container-visible file.
// Path may be relative to the workspace or an absolute /workspace path; the
// runtime normalizes it and rejects traversal before contacting the engine.
type WorkspaceFileWriteRequest struct {
	Path    string
	Content io.Reader
	Size    int64
}

// RuntimeWorkspaceFileWriter is the controlled control-plane-to-workspace
// import boundary used by chat uploads and container filesystem tools.
// Implementations must never accept a provider/container ID from callers.
type RuntimeWorkspaceFileWriter interface {
	WriteWorkspaceFile(ctx context.Context, spec RuntimeSpec, request WorkspaceFileWriteRequest) (string, error)
}

// RuntimeInspector exposes read-only engine and image checks. Keeping this
// boundary separate allows health/readiness code to be tested before lifecycle
// mutations are enabled.
type RuntimeInspector interface {
	EngineInfo(ctx context.Context) (EngineInfo, error)
	InspectManifest(ctx context.Context, image ImageReference) (ImageInspection, error)
	InspectLocalImage(ctx context.Context, image ImageReference) (ImageInspection, error)
	VerifyRuntimeImage(ctx context.Context, providerID string, image ImageReference) (ImageInspection, error)
}

// RuntimeCreator is the narrow creation slice used by the asynchronous
// initializer. Lifecycle handlers depend on RuntimeManager instead.
type RuntimeCreator interface {
	RuntimeInspector
	Create(ctx context.Context, spec RuntimeSpec) (Runtime, error)
}

// RuntimeReadinessChecker validates engine-observed state and the trusted
// image inventory before a created runtime can be exposed as ready.
type RuntimeReadinessChecker interface {
	ValidateReadiness(ctx context.Context, runtime Runtime, spec RuntimeSpec) (ReadinessReport, error)
}

// RuntimeManager is the only lifecycle boundary the application may use for
// conversation containers. Handlers and Agent execution paths must depend on
// this interface instead of invoking Docker CLI commands directly.
type RuntimeManager interface {
	RuntimeInspector
	Create(ctx context.Context, spec RuntimeSpec) (Runtime, error)
	Inspect(ctx context.Context, id RuntimeID) (Runtime, error)
	ListOwned(ctx context.Context) ([]Runtime, error)
	Start(ctx context.Context, id RuntimeID) (Runtime, error)
	Stop(ctx context.Context, id RuntimeID, options StopOptions) (Runtime, error)
	Rebuild(ctx context.Context, id RuntimeID, options RebuildOptions) (Runtime, error)
	Delete(ctx context.Context, id RuntimeID, options DeleteOptions) error
}
