package container

import (
	"context"
	"errors"
	"time"
)

// RuntimeID is the CyberStrikeAI-owned identifier for a conversation runtime.
// It is intentionally separate from the Docker container ID exposed by an
// engine implementation.
type RuntimeID string

// Status describes the control-plane view of a conversation runtime.
type Status string

const (
	StatusCreating Status = "creating"
	StatusStopped  Status = "stopped"
	StatusStarting Status = "starting"
	StatusRunning  Status = "running"
	StatusStopping Status = "stopping"
	StatusFailed   Status = "failed"
)

// NetworkMode is deliberately closed. Phase 1 only permits NetworkNone; the
// internal egress-gateway mode is reserved for the later boundary phase.
type NetworkMode string

const (
	NetworkNone     NetworkMode = "none"
	NetworkInternal NetworkMode = "internal"
)

var (
	ErrNotFound             = errors.New("container runtime not found")
	ErrAlreadyExists        = errors.New("container runtime already exists")
	ErrEngineUnavailable    = errors.New("container engine unavailable")
	ErrInvalidSpecification = errors.New("invalid container runtime specification")
	ErrArchitectureMismatch = errors.New("container image architecture mismatch")
	ErrImageDigestMismatch  = errors.New("container image digest mismatch")
	ErrRuntimeStateConflict = errors.New("container runtime state conflict")
)

// EngineInfo is a read-only description of the connected container engine.
type EngineInfo struct {
	Available    bool
	Version      string
	Architecture string
	OperatingSys string
}

// ImageReference requires an immutable digest in addition to the repository.
// Tags may be displayed by the UI, but implementations must create containers
// from Repository@Digest and verify ResolvedDigest before reporting readiness.
type ImageReference struct {
	Repository     string
	Digest         string
	Platform       string
	ResolvedDigest string
}

// ResourceLimits contains the limits that every runtime implementation must
// enforce. Zero is not interpreted as unlimited; validation rejects it.
type ResourceLimits struct {
	NanoCPUs          int64
	MemoryBytes       int64
	PIDs              int64
	NoFileSoft        uint64
	NoFileHard        uint64
	WorkspaceBytes    int64
	MaxConcurrentExec int
}

// SecurityProfile describes non-negotiable container isolation controls.
// The Docker implementation will translate this contract into engine options.
type SecurityProfile struct {
	ReadOnlyRootFS      bool
	NoNewPrivileges     bool
	DropAllCapabilities bool
	NetworkMode         NetworkMode
	SeccompProfile      string
	TmpfsBytes          int64
}

// WorkspaceSpec makes persistence and deletion independent from the container
// lifecycle. VolumeName is generated by the control plane, never supplied by a
// user as an arbitrary host path.
type WorkspaceSpec struct {
	Persistent bool
	VolumeName string
	MountPath  string
}

// RuntimeSpec is the desired immutable specification for one conversation.
type RuntimeSpec struct {
	ID             RuntimeID
	ConversationID string
	Image          ImageReference
	Resources      ResourceLimits
	Security       SecurityProfile
	Workspace      WorkspaceSpec
}

// Runtime is the engine-observed state returned to the control plane.
type Runtime struct {
	ID             RuntimeID
	ConversationID string
	ProviderID     string
	Image          ImageReference
	Status         Status
	CreatedAt      time.Time
	UpdatedAt      time.Time
	LastError      string
}

type StopOptions struct {
	Timeout time.Duration
}

type DeleteOptions struct {
	RemoveWorkspace bool
}

type RebuildOptions struct {
	Spec            RuntimeSpec
	RemoveWorkspace bool
}

// RuntimeManager is the only lifecycle boundary the application may use for
// conversation containers. Handlers and Agent execution paths must depend on
// this interface instead of invoking Docker CLI commands directly.
type RuntimeManager interface {
	EngineInfo(ctx context.Context) (EngineInfo, error)
	Create(ctx context.Context, spec RuntimeSpec) (Runtime, error)
	Inspect(ctx context.Context, id RuntimeID) (Runtime, error)
	ListOwned(ctx context.Context) ([]Runtime, error)
	Start(ctx context.Context, id RuntimeID) (Runtime, error)
	Stop(ctx context.Context, id RuntimeID, options StopOptions) (Runtime, error)
	Rebuild(ctx context.Context, id RuntimeID, options RebuildOptions) (Runtime, error)
	Delete(ctx context.Context, id RuntimeID, options DeleteOptions) error
}
